project:
  type: website

website:
  title: "Demand Curve Estimation"
  navbar:
    left:
      - href: non-regression-demand.qmd
        text: Distribution Demand
        
format:
  html:
    theme: cosmo
    toc: true